In [37]:
import numpy as np
from scipy import signal
from random import randint

In [179]:
def normalize_figure(figure):
    # print(figure)
    min_idx = np.argmin(figure, axis=0)
    min_i, min_j = figure[min_idx]
    min_i = min_i[0]
    min_j = min_j[1]

    # print(figure[min_idx])
    # print(min_i, min_j)

    
    boxed_figure = np.array([np.array((tup[0]-min_i, tup[1]-min_j)) for tup in figure])
    return (boxed_figure)

def generate_figure(size: int, max_skip: int = 0):
    last_painted = np.array((0,0))
    painted = 1
    skips_made = 0
    figure = np.zeros((size,2))
    figure[0] = last_painted
    moves = [lambda i, j: (i+1, j),
     lambda i, j: (i+1, j+1),
     lambda i, j: (i+1, j-1),
     lambda i, j: (i, j+1),
     lambda i, j: (i, j-1),
     lambda i, j: (i-1, j),
     lambda i, j: (i-1, j+1),
     lambda i, j: (i-1, j-1)
     ]
    while painted != size:
        next_move = randint(0, len(moves)-1)
        painted_proposal = np.array(moves[next_move](*last_painted))
        if painted in figure:
            continue
        last_painted = painted_proposal
        # print(last_painted)
        figure[painted] = last_painted.copy()

        painted += 1

    # print(figure)
    return normalize_figure(figure)
# generate_figure(4)
def is_in_figures(in_fig, figures):
    if len(figures) == 0:
        return False

    for fig in figures:
        # is_in |= (fig == figure)
        count = 0
        # print("a"*100)
        # print(fig, in_fig)
        for in_piece in in_fig:
            # print("b"*100)

            # print(piece is in fig)
            # print(piece)

            for piece in fig:
                # print(in_piece, piece, in_piece[0] == piece[0] and in_piece[1] == piece[1])
                if ((in_piece[0] == piece[0]) and (in_piece[1] == piece[1])):
                    count+=1
                    continue
            
        # print(count, len(in_fig))
        if count == len(in_fig):
            return True

    return False
# a =([[0,0]])

def generate_figures(size: int, fig_count: int, max_skip: int = 0):
    # figures = np.zeros((fig_count, size, 2))
    last_figure = 0
    figures = []
    for i in range(fig_count):
        figure=generate_figure(size)
        # print(figure)
        # print(figures)
        # print(figure not in figures)
        if not is_in_figures(figure, figures):

            figures.append(figure)
            # figures[last_figure] = figure.copy()
            # last_figure += 1
    return figures
figs = generate_figures(4, 1000)
for i in (figs):
    print(i)
# print(figs)
        


KeyboardInterrupt: 

In [171]:
fig_a = np.array([[1,0, 0], 
                  [1,0, 0], 
                  [1,0, 0], 
                  [1,0, 0]])
fig_b = np.array([[0,1, 0], 
                  [0,1, 0], 
                  [0,1, 0]])
print(fig_a.shape)
print(is_in_figures(fig_a, [fig_a]))

def confine(fig: np.array(np.array)):

    max_i = -1
    min_i =  float("inf")
    max_j = -1
    min_j = float("inf")

    coords = []
    for i, row in enumerate(fig):
        for j, el in enumerate(row):
            if el == 1:
                coords.append((i,j))
                # print(i, j)
                max_i = max(max_i, i)
                max_j = max(max_j, j)
                min_i = min(min_i, i)
                min_j = min(min_j, j)
    
    # print(max_i, min_i, max_j, max_j)
    boxed_figure = [(tup[0]-min_i, tup[1]-min_j) for tup in coords]
    return boxed_figure

    # [for i in range(fig.shape[i])]
print(confine(fig_b))



(4, 3)
4 4
True
[(0, 0), (1, 0), (2, 0)]


In [26]:
print(np.corrcoef(x,y))
corr = (signal.correlate2d(x, y, mode='same'))
b, a = np.unravel_index(np.argmax(corr), corr.shape)
print(b, a)

[[ 1.   1.   1.  -0.5 -0.5 -0.5]
 [ 1.   1.   1.  -0.5 -0.5 -0.5]
 [ 1.   1.   1.  -0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5  1.   1.   1. ]
 [-0.5 -0.5 -0.5  1.   1.   1. ]
 [-0.5 -0.5 -0.5  1.   1.   1. ]]
1 0
