In [49]:
import numpy as np
from scipy import signal
from random import randint
import pandas as pd

In [53]:
def normalize_figure(figure):
    # print(figure)
    min_idx = np.argmin(figure, axis=0)
    min_i, min_j = figure[min_idx]
    min_i = min_i[0]
    min_j = min_j[1]

    # print(figure[min_idx])
    # print(min_i, min_j)

    
    boxed_figure = np.array([np.array((tup[0]-min_i, tup[1]-min_j)) for tup in figure])
    return (boxed_figure)

def generate_figure(size: int, max_skip: int = 0):
    last_painted = np.array((0,0))
    painted = 1
    skips_made = 0
    figure = np.zeros((size,2))
    figure[0] = last_painted
    moves = [lambda i, j: (i+1, j),
     lambda i, j: (i+1, j+1),
     lambda i, j: (i+1, j-1),
     lambda i, j: (i, j+1),
     lambda i, j: (i, j-1),
     lambda i, j: (i-1, j),
     lambda i, j: (i-1, j+1),
     lambda i, j: (i-1, j-1)
     ]
    while painted < size:
        next_move = randint(0, len(moves)-1)
        painted_proposal = np.array(moves[next_move](*last_painted))
        # np.isin(figure, painted_proposal)
        if (painted_proposal == figure).all(1).any():
            continue
        last_painted = painted_proposal
        # print(last_painted)
        figure[painted] = last_painted.copy()

        painted += 1

    # print(figure)
    return normalize_figure(figure)
# generate_figure(4)
def is_in_figures(in_fig, figures):
    if len(figures) == 0:
        return False
    close = False
    for fig in figures:
        close |= np.allclose(fig, in_fig)
    return close
# a =([[0,0]])

def generate_figures(size: int, fig_count: int, max_skip: int = 0):
    figures = []
    for i in range(fig_count):
        figure = generate_figure(size)
        if not is_in_figures(figure, figures):
            figures.append(figure)
    return figures

# figs = generate_figures(6, 1000)
# for i in (figs):
    # print(i)
# print(figs)
        


In [54]:
figures = np.array(generate_figures(6, 1000))

In [55]:
def figures_to_csv(figures: np.array(np.array(np.array))):
    two_d =  np.array(list([np.array(list([item for sublist in figure for item in sublist])) for figure in figures]))

#     DF = pd.DataFrame(two_d)
# # # save the dataframe as a csv file
#     DF.to_csv(f"figures_size{len(two_d[0])}.csv")
    np.savetxt(f"figures_size{len(two_d[0])//2}.csv", two_d,
                delimiter = ",", fmt='%1.0f')
figures_to_csv(figures)

In [63]:
c = [4,0,3,1,2,0,2,1,1,2,0,2]
a = np.zeros((len(c)//2,len(c)//2))

b = [(c[i], c[i+1]) for i in range(0, len(c)-1, 2)]
# b = [(1,0) ,(0,1), (1,2), (2,2), (1,1) ,(0,2)]
print(b)
for i,j in b:
    print(i,j)
    a[i,j]=1

print (a)


[(4, 0), (3, 1), (2, 0), (2, 1), (1, 2), (0, 2)]
4 0
3 1
2 0
2 1
1 2
0 2
[[0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
fig_a = np.array([[1,0, 0], 
                  [1,0, 0], 
                  [1,0, 0], 
                  [1,0, 0]])
fig_b = np.array([[0,1, 0], 
                  [0,1, 0], 
                  [0,1, 0]])
print(fig_a.shape)
print(is_in_figures(fig_a, [fig_a]))
print(np.allclose(fig_a, fig_a))
def confine(fig: np.array(np.array)):

    max_i = -1
    min_i =  float("inf")
    max_j = -1
    min_j = float("inf")

    coords = []
    for i, row in enumerate(fig):
        for j, el in enumerate(row):
            if el == 1:
                coords.append((i,j))
                # print(i, j)
                max_i = max(max_i, i)
                max_j = max(max_j, j)
                min_i = min(min_i, i)
                min_j = min(min_j, j)
    
    # print(max_i, min_i, max_j, max_j)
    boxed_figure = [(tup[0]-min_i, tup[1]-min_j) for tup in coords]
    return boxed_figure

    # [for i in range(fig.shape[i])]
print(confine(fig_b))



(4, 3)
True
True
[(0, 0), (1, 0), (2, 0)]


In [4]:
print(np.corrcoef(x,y))
corr = (signal.correlate2d(x, y, mode='same'))
b, a = np.unravel_index(np.argmax(corr), corr.shape)
print(b, a)

NameError: name 'x' is not defined