In [68]:
import numpy as np
from scipy import signal
from random import randint
from random import random
import pandas as pd

In [81]:
def normalize_figure(figure):
    # print(figure)
    min_idx = np.argmin(figure, axis=0)
    min_i, min_j = figure[min_idx]
    min_i = min_i[0]
    min_j = min_j[1]

    # print(figure[min_idx])
    # print(min_i, min_j)

    
    boxed_figure = np.array([np.array((tup[0]-min_i, tup[1]-min_j)) for tup in figure])
    return (boxed_figure)

def generate_figure(size: int, max_skip: int = 0):
    last_painted = np.array((0,0))
    painted = 1
    skips_made = 0
    figure = np.zeros((size,2))
    figure[0] = last_painted
    moves = [lambda i, j: (i+1, j),
             lambda i, j: (i+1, j+1),
             lambda i, j: (i+1, j-1),
             lambda i, j: (i, j+1),
             lambda i, j: (i, j-1),
             lambda i, j: (i-1, j),
             lambda i, j: (i-1, j+1),
             lambda i, j: (i-1, j-1)
             ]
    while painted < size:
        next_move = randint(0, len(moves)-1)
        painted_proposal = np.array(moves[next_move](*last_painted))
        if (painted_proposal == figure).all(1).any(): # painting proposal in figure
            continue
        last_painted = painted_proposal
        if random() > 0.80 and skips_made < max_skip:
            skips_made+=1
            continue
        figure[painted] = last_painted.copy()

        skips_made-=1
        painted += 1

    return normalize_figure(figure)
# generate_figure(4)
def is_in_figures(in_fig, figures):
    if len(figures) == 0:
        return False
    close = False
    for fig in figures:
        close |= np.allclose(fig, in_fig)
    return close
# a =([[0,0]])

def generate_figures(size: int, fig_count: int, max_skip: int = 0):
    figures = []
    for i in range(fig_count):
        figure = generate_figure(size, max_skip)
        if not is_in_figures(figure, figures):
            figures.append(figure)
    return figures

# figs = generate_figures(6, 1000)
# for i in (figs):
    # print(i)
# print(figs)
        


In [86]:
figures = np.array(generate_figures(6, 1000, 1))

In [87]:
def figures_to_csv(figures: np.array(np.array(np.array))):
    two_d =  np.array(list([np.array(list([item for sublist in figure for item in sublist])) for figure in figures]))

#     DF = pd.DataFrame(two_d)
# # # save the dataframe as a csv file
#     DF.to_csv(f"figures_size{len(two_d[0])}.csv")
    np.savetxt(f"figures_size_{len(two_d[0])//2}.csv", two_d,
                delimiter = ",", fmt='%1.0f')
figures_to_csv(figures)

In [109]:
from PIL import Image as im
c = [2,5,1,4,0,3,0,2,0,1]
a = np.zeros((len(c),len(c)), np.uint8)

b = [(c[i], c[i+1]) for i in range(0, len(c)-1, 2)]
# b = [(1,0) ,(0,1), (1,2), (2,2), (1,1) ,(0,2)]
print(b)

for i,j in b:
    print(i,j)
    a[i,j]=1
data = im.fromarray(a)

      
    # saving the final output 
    # as a PNG file
print (a)
# data.save('gfg_dummy_pic.png')



[(2, 5), (1, 4), (0, 3), (0, 2), (0, 1)]
2 5
1 4
0 3
0 2
0 1
[[0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [124]:
fig_a = np.array([[1,0, 0], 
                  [1,0, 0], 
                  [1,0, 0], 
                  [1,0, 0]])
fig_b = np.array([[0,1, 0], 
                  [0,1, 0], 
                  [0,1, 0]])
print(fig_a.shape)
print(is_in_figures(fig_a, [fig_a]))
print(np.allclose(fig_a, fig_a))
def confine(fig: np.array(np.array)):

    max_i = -1
    min_i =  float("inf")
    max_j = -1
    min_j = float("inf")

    coords = []
    for i, row in enumerate(fig):
        for j, el in enumerate(row):
            if el == 1:
                coords.append((i,j))
                # print(i, j)
                max_i = max(max_i, i)
                max_j = max(max_j, j)
                min_i = min(min_i, i)
                min_j = min(min_j, j)
    
    # print(max_i, min_i, max_j, max_j)
    boxed_figure = [(tup[0]-min_i, tup[1]-min_j) for tup in coords]
    return boxed_figure

    # [for i in range(fig.shape[i])]
b_ne = [[1, 1, 1, 0, 0, 0, 0, 1, 1, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
     [1, 0, 0, 0, 0, 0, 0, 1, 1, 1],
     [1, 1, 1, 0, 0, 0, 0, 1, 0, 0]]
b_nw = [[1, 1, 1, 0, 0, 0, 0, 0, 1, 1],
     [1, 0, 0, 0, 0, 0, 0, 1, 1, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 1, 1, 0, 0, 0, 0, 1, 1, 1]]
b_sw = [[1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
     [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 1, 1, 0, 0, 0, 0, 1, 1, 1]]
b_se = [[1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
     [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
     [1, 1, 0, 0, 0, 0, 0, 1, 1, 1]]
res = (confine(b_se))
fin_res = [item for sublist in res for item in sublist]

values = " ".join((str(i) for i in fin_res))
print(values)


(4, 3)
True
True
0 0 0 1 0 7 0 8 0 9 1 0 1 2 1 9 2 0 2 8 7 1 7 8 8 1 8 2 8 9 9 0 9 1 9 7 9 8 9 9
